#!/bin/bash
#
# PreToolUse hook for Edit and Write. Blocks file operations outside the
# project directory so another project's hooks are never silently skipped.
# Fails closed: if it cannot determine the path, it blocks.

set -uo pipefail

deny() {
  echo "BLOCKED by guard-scope: $1" >&2
  exit 2
}

INPUT=$(cat)
[ -n "$INPUT" ] || deny "no input received. Failing closed."

FILE_PATH=""
if command -v jq >/dev/null 2>&1; then
  FILE_PATH=$(printf '%s' "$INPUT" | jq -r '.tool_input.file_path // empty' 2>/dev/null) || \
    deny "jq failed to parse hook input. Failing closed."
elif command -v python3 >/dev/null 2>&1; then
  FILE_PATH=$(printf '%s' "$INPUT" | python3 -c \
    'import sys,json; print(json.load(sys.stdin).get("tool_input",{}).get("file_path",""))' 2>/dev/null) || \
    deny "python3 failed to parse hook input. Failing closed."
else
  deny "no JSON parser available (need jq or python3). Failing closed."
fi

[ -n "$FILE_PATH" ] || deny "could not extract file_path. Failing closed."

# Every rule below is a glob against FILE_PATH. Until BOOT-66 that glob ran on the path exactly as
# the tool supplied it, so inserting `/./` or `dir/../` defeated ALL of them at once, including the
# one keeping writes inside the project. settings.json's deny list is entirely in-project `./**`
# patterns and permissions.deny does not bind Bash at all, so for a write into a sibling repo this
# hook is the only thing there is. Two characters were enough.
#
# Collapsed textually rather than with realpath or `cd`: a Write creates a file that does not exist
# yet, and both of those need the path to be there already. Fails closed on anything unresolvable.
case "$FILE_PATH" in
  /*) ;;
  *) deny "file_path '$FILE_PATH' is not absolute, so it cannot be judged against the project root. Failing closed." ;;
esac
normalise_path() {
  np_out=""
  np_saved_ifs=$IFS
  IFS=/
  set -- $1
  IFS=$np_saved_ifs
  for np_seg in "$@"; do
    case "$np_seg" in
      ''|.) ;;
      ..)   np_out="${np_out%/*}" ;;
      *)    np_out="$np_out/$np_seg" ;;
    esac
  done
  printf '%s' "${np_out:-/}"
}
FILE_PATH=$(normalise_path "$FILE_PATH")
[ -n "$FILE_PATH" ] || deny "path normalisation produced nothing. Failing closed."

PROJECT_DIR="${CLAUDE_PROJECT_DIR:-$(pwd)}"
RESOLVED=$(cd "$PROJECT_DIR" 2>/dev/null && pwd -P)

case "$FILE_PATH" in
  "$RESOLVED"/*) ;;
  *) deny "file '$FILE_PATH' is outside this project ($RESOLVED). Launch Claude from the target project so its hooks fire." ;;
esac

# Self-protection: the agent may not edit its own enforcement layer or the gate that judges
# it. If it could edit these, none of the blocks bind (R6). settings.json denies them silently;
# this makes the block explain itself.
case "$FILE_PATH" in
  "$RESOLVED"/.claude/*|"$RESOLVED"/template/.claude/*)
    deny "the .claude enforcement layer is protected: the agent cannot edit its own hooks, settings or deny rules (R6, self-protection). A human changes these in _bootstrap and they re-vendor." ;;
  "$RESOLVED"/scripts/conform.sh|"$RESOLVED"/scripts/gate-baseline.sh|"$RESOLVED"/scripts/gate-status.sh|"$RESOLVED"/scripts/tree-fingerprint.sh)
    deny "this is a gate script; the agent cannot edit what verifies it (R6). A human changes it in _bootstrap and it re-vendors." ;;
  "$RESOLVED"/*.pbxproj|"$RESOLVED"/*.xcodeproj/*)
    deny "the project file is generated by XcodeGen from project.yml, never edited (FD-0001)." ;;
  "$RESOLVED"/Config.xcconfig)
    deny "Config.xcconfig holds API keys; the agent may not edit it." ;;
esac

# CLAUDE.md is loaded on every turn in this repo, so a change to it changes how every future
# session behaves. An agent proposes; a human decides. One-shot token, same shape as the
# CHANGED override: it is consumed by the edit, so each change needs a fresh human action.
case "$FILE_PATH" in
  "$RESOLVED"/CLAUDE.md|"$RESOLVED"/template/CLAUDE.md)
    if [ -f "$RESOLVED/.claude/allow-claude-md-edit" ]; then
      rm -f "$RESOLVED/.claude/allow-claude-md-edit"
    else
      deny "CLAUDE.md loads on every turn, so editing it changes every future session. Do not edit it. Tell the human exactly what line you would change, what it would say, and why it belongs in an always-loaded file rather than in .claude/rules/, a skill, an ADR or the ticket. If they agree they will run: touch .claude/allow-claude-md-edit"
    fi ;;
esac

# Archived documents are finished. An agent may not edit or add to one, because a document
# that is being maintained is not archived. See FD-0011.
case "$FILE_PATH" in
  "$RESOLVED"/docs/archive/*)
    deny "docs/archive/ holds finished documents and is not maintained. Do not edit or add to one. If the thing you learned is still true, it belongs in .claude/rules/, a runbook, or an ADR (FD-0011)." ;;
esac

# The decision log is read-only to agents, except proposed/. An FD- decision is authored
# only in _bootstrap and approved by a human; an app (AD-) decision is also human-approved
# from a proposal. This is the Edit/Write tool route. guard-bash covers PART of the shell route:
# a path assembled from variables defeats it, so do not read this as complete (BOOT-113).
case "$FILE_PATH" in
  "$RESOLVED"/docs/decisions/proposed/*) ;;
  "$RESOLVED"/template/docs/decisions/proposed/*) ;;
  "$RESOLVED"/docs/decisions/*|"$RESOLVED"/template/docs/decisions/*)
    deny "the decision log is read-only to agents. An FD- decision is authored ONLY in _bootstrap and approved by a human, and an app AD- decision is also human-approved. Do not create it here. Put your proposal in docs/decisions/proposed/ and ask the human to author and approve it (FD-0000)." ;;
esac

exit 0
